name: Render Mermaid Diagrams

on:
  push:
    paths:
      - 'docs/diagrams/*.mmd'
      - 'README.md'
      - '.github/workflows/diagrams.yml'
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Render diagrams
        run: |
          mkdir -p docs/diagrams/png
          docker run --rm -u `id -u`:`id -g` -v "$PWD":/data minlag/mermaid-cli:latest -i /data/docs/diagrams/*.mmd -o /data/docs/diagrams/png/ -b transparent || true
          # Fallback: fix any missing files with individual processing
          for f in docs/diagrams/*.mmd; do \
            n=$(basename "$f" .mmd); \
            if [ ! -f "docs/diagrams/png/$n.png" ]; then \
              docker run --rm -u `id -u`:`id -g` -v "$PWD":/data minlag/mermaid-cli:latest -i "/data/$f" -o "/data/docs/diagrams/png/$n.png" -b transparent || true; \
            fi \
          done

      - name: Commit diagrams
        env:
          GIT_AUTHOR_NAME: github-actions[bot]
          GIT_AUTHOR_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
          GIT_COMMITTER_NAME: github-actions[bot]
          GIT_COMMITTER_EMAIL: 41898282+github-actions[bot]@users.noreply.github.com
        run: |
          if ! git diff --quiet; then
            git add docs/diagrams/png/*.png || true
            git commit -m "chore(diagrams): update rendered PNG diagrams"
            git push
          fi

